# Generated by Django 3.0.7 on 2020-06-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200622_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='link',
        ),
        migrations.AddField(
            model_name='car',
            name='carpic',
            field=models.ImageField(blank=True, default='default.png', upload_to='Cars'),
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Car')),
            ],
        ),
    ]
