# Generated by Django 3.0.7 on 2020-06-23 07:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200622_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
