# Generated by Django 3.0.7 on 2020-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default='#', max_length=1000),
            preserve_default=False,
        ),
    ]
