# Generated by Django 3.0.7 on 2020-06-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200613_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_link',
            field=models.CharField(blank=True, default='#', max_length=1000),
        ),
    ]
