# Generated by Django 3.0.7 on 2020-06-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, default='member', max_length=100)),
                ('subsystem', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
