# Generated by Django 3.0.7 on 2020-06-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='linked_in',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='Team_profile_pics'),
        ),
    ]
