# Generated by Django 3.0.7 on 2020-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200615_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quote1',
            field=models.CharField(default='SASTRA Racing Team', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='quote2',
            field=models.CharField(blank=True, default='SASTRA Racing Team', max_length=100),
        ),
    ]
