# Generated by Django 3.0.7 on 2020-06-20 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200617_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
