# Generated by Django 3.0.7 on 2020-06-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200620_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
