# Generated by Django 3.0.7 on 2020-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200620_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='backgroundimage3',
            field=models.ImageField(blank=True, default='default.png', upload_to='back3'),
        ),
        migrations.AddField(
            model_name='item',
            name='team_background',
            field=models.ImageField(blank=True, default='back2.jpg', upload_to='team'),
        ),
    ]
